### ISSUE TITLE
自定义view的状态没有保存和恢复

### ISSUE THREAD

**Issue by SuperChandler** [Mr-XiaoLiang/LView-AS#2]
就以LProgressButton为例吧， 如果我点击 ” 开始“ 按钮， 按钮状态改变成进度条
此时，如果我将屏幕旋转。
然后，再次进入此界面后，LProgressButton 又回到了初始状态的“开始”按钮

**Comment by Mr-XiaoLiang** [comment]
对于你说的这个问题，很抱歉，确实是我没有考虑到，因为当初写这个View的时候，我刚刚入行一年多，涉入不深。不过要实现这个功能也非常容易的，也可以在View内或者View外，保存状态，然后再在合适的位置，恢复即可。因为我View都是以状态为单位的，所以只需要记录几个数据值就好了。

**Comment by SuperChandler** [comment]
@Mr-XiaoLiang 嗯，我是想在view内保存状态，是通过onSaveInstanceState和onRestoreInstanceState方法来保存和恢复么？

**Comment by Mr-XiaoLiang** [comment]
可以啊，可以根据自己的需求来在你需要的地方保存啊。

**Comment by SuperChandler** [comment]
嗯嗯 好的  谢谢
